modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="mixintemplate"
version="${file.jarVersion}"
displayName="DISPLAYNAME"
logoFile="mod-logo.png" #optional
authors="3x1t_5tyl3" #optional
description='''
Random stuff here explain the mod or smth idk
'''

[[dependencies.mixintemplate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mixintemplate]] #optional
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mixintemplate]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.3.7,11.0.0)"
    ordering="AFTER"
    side="BOTH"